name: Deploy Prefect Flows

on:
  push:
    branches:
      - main
      - dev*
      - feature/*
    paths-ignore:
      - "dbt/**"
      - "profiles.yml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "dbt/**"
      - "profiles.yml"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  REPOSITORY_NAME: prefect-images # Change to your repository name or create it
  BASE_IMAGE_NAME: project-image # Change to your project name
  GITHUB_SHA: ${{ github.sha }}
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "TAG=$ENVIRONMENT-$GITHUB_SHA" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "IMAGE_NAME=$BASE_IMAGE_NAME-$ENVIRONMENT" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_DOCKER }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Debug environment variables
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "ENVIRONMENT: ${{ env.ENVIRONMENT }}"
          echo "Is main branch: ${{ github.ref == 'refs/heads/main' }}"

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: runtime # Target the runtime stage
          cache-from: type=registry,ref=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:cache,mode=max
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            ENVIRONMENT=${{ env.ENVIRONMENT }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup UV
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Dependencies
        run: |
          uv pip install --system .

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          python pipelines/deploy_flows.py
